version: '3.8'
services:
  order-service:
    build: .
    image: order-service
    container_name: order-service-container
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: OrderService
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5430/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1

    volumes:
      - ./pgdata:/var/lib/postgresql/data/

    restart: unless-stopped
    tty: true
    stdin_open: true
volumes:
  pgdata: