spring:
    application:
        name: OrderService
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 1
        url: jdbc:postgresql://localhost:5432/postgres
    sql:
        init:
            mode: always
            schema-locations: classpath*:static/db/init.sql
            data-locations: classpath*:static/db/data.sql
server:
    port: 8080