spring:
    application:
        name: OrderService
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: 1
        url: jdbc:postgresql://postgres-db:5430/postgres
    liquibase:
        enabled: true
        change-log: classpath*:db/db.changelog-master.yaml
server:
    port: 8080